using System.Runtime.Serialization;

namespace OCPI.Contracts
{
    public enum TokenType : byte
    {
        /// <summary>
        /// One time use Token ID generated by a server (or App.) The eMSP uses this to bind a Session to a
        /// customer, probably an app user.
        /// </summary>
        [EnumMember(Value = "AD_HOC_USER")]
        AdHocUser = 11,

        /// <summary>
        /// Token ID generated by a server (or App.) to identify a user of an App. The same user uses the
        /// same Token for every Session.
        /// </summary>
        [EnumMember(Value = "APP_USER")]
        AppUser = 12,

        //======================================

        /// <summary>
        /// RFID token
        /// </summary>
        [EnumMember(Value = "RFID")]
        Rfid = 21,

        //======================================

        /// <summary>
        /// Other type of token
        /// </summary>
        [EnumMember(Value = "OTHER")]
        Other = 255
    }
}
